"""empty message

Revision ID: 37914ed4a54d
Revises: None
Create Date: 2014-02-24 11:02:06.329007

"""

# revision identifiers, used by Alembic.
revision = '37914ed4a54d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
