API_URL = "https://api.twitter.com"
REQUEST_TOKEN_URL = API_URL + "/oauth/request_token"
AUTHORIZE_URL = API_URL + "/oauth/authorize?oauth_token={request_token}"
ACCESS_TOKEN_URL = API_URL + "/oauth/access_token"
TIMELINE_URL = API_URL + "/1.1/statuses/home_timeline.json"
UPDATE_URL = API_URL + "/1.1/statuses/update.json"
REVERSE_GEOCODE_URL = API_URL + "/1.1/geo/reverse_geocode.json"
TRENDS_URL = API_URL + "/1.1/trends/place.json"
